name: Deploy to AWS EBS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #DEPLOY_PACKAGE_NAME: ${{ secrets. }}
  DEPLOY_PACKAGE_NAME: deployed.zip
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
  EB_APP_ENV_NAME: ${{ secrets.EB_APP_ENV_NAME }}
  AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and test the Docker image
      run: |-
          echo Building Image and running Tests
          docker build ./client --file ./client/Dockerfile.dev --tag sanim16/multi-docker-react
          docker run -e CI=true sanim16/multi-docker-react npm run test -- --coverage
          echo Finished running tests successfully
      #working-directory: ./ ##not required as docker command is setup to run in the specific directory
    - name: Post test build
      run: |-
          echo Building production Images
          docker build ./client -t sanim16/multi-client
          docker build ./nginx -t sanim16/multi-nginx
          docker build ./server -t sanim16/multi-server
          docker build ./worker -t sanim16/multi-worker
          echo built images
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Images to Docker Hub
      run: |-
          echo Pushing production Images to Docker Hub
          docker push sanim16/multi-client
          docker push sanim16/multi-nginx
          docker push sanim16/multi-server
          docker push sanim16/multi-worker
          echo built images
  deploy-to-elasticbeanstalk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      
      - name: Generate deployment package by compressing build to ZIP file
        run: zip -r deployed.zip . -x '*.git*'
        #zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x '*.git*'  ##used to replace the zip command above with variable name
        ##instead of hardcoding name
        
        
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.AWS_BUCKET_NAME }}
          
      - name: Create new ElasticBeanStalk Version
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ env.EB_APPLICATION_NAME }} --version-label "Ver-${{ github.sha }}" --description "${{ github.sha }}" --source-bundle S3Bucket=${{ env.AWS_BUCKET_NAME }},S3Key=${{ env.DEPLOY_PACKAGE_NAME }} --auto-create-application
      
      - name: deploy new version to EBS
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_APP_ENV_NAME }} --version-label "Ver-${{ github.sha }}"
